package com.briozing.automation.utils;

public enum TestSteps {

    STEP_GET_ALL_COUNTRIES,
    STEP_GET_COUNTRY_BY_NAME,
    STEP_GET_COUNTRY_BY_FULL_NAME,
    STEP_GET_COUNTRY_BY_ALPHACODE,
    STEP_GET_COUNTRY_BY_CAPITAL,
    STEP_GET_COUNTRY_BY_CURRENCY

}
